# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Quotes Pipeline DAB

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "mkdocs.yml"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  THRESHOLD_TESTS: 80

jobs:
  build:
    name: "Build, Linting, Tests"
    env:
      API_KEY_NINJAS: ${{ secrets.API_KEY_NINJAS }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Poetry version 1.5.1
        run: |
          pip install poetry==1.5.1

      - name: Install dev dependencies
        run: |
          poetry install --without doc

      - name: Run Tests - Pytest and Coverage
        run: |
          poetry run pytest --cov=quotes_dab --cov-report=term-missing --cov-fail-under=$THRESHOLD_TESTS tests/

      - name: Build Artifact Wheel
        run: |
          poetry build --format=wheel

      - name: Check folder
        run: |
          echo $(ls)

      - uses: actions/upload-artifact@v3
        with:
          name: quotes_dab
          path: dist/*.whl

  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    needs: build
    env:
      DATABRICKS_PROFILE: ${{ vars.DATABRICKS_PROFILE }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      # Checkout
      - uses: actions/checkout@v3

      - name: Generate .databrickscfg
        run: |
          FILE_NAME=".databrickscfg"
          echo "$DATABRICKS_PROFILE" > $FILE_NAME
          echo "host = $DATABRICKS_HOST" >> $FILE_NAME
          echo "token = $DATABRICKS_TOKEN" >> $FILE_NAME

      - name: Download quotes_dab artifact
        uses: actions/download-artifact@v3
        with:
          name: quotes_dab
          path: ./dist/

      - name: Check folder
        run: |
          echo $(ls)

        # Download the Databricks CLI.
        # See https://github.com/databricks/setup-cli
      - name: Download Databricks CLI
        uses: databricks/setup-cli@main

      # Deploy the bundle to the "prod" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy
        working-directory: .
