name: Update Mkdocs and GitHub Pages

on:
  push:
    paths:
      - "mkdocs.yml"
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    name: Setup Poetry and Doc Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Poetry version 1.5.1
        run: |
          pip install poetry==1.5.1

      - name: Git Fetch
        run: |
          git fetch

      - name: Install documentation dependencies
        run: |
          poetry install --only doc

      - name: Update Github Pages
        run: |
          poetry run mkdocs gh-deploy
